# Generated by Django 4.0.3 on 2022-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_alter_order_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderupdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
