# Generated by Django 4.0.3 on 2022-05-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_updatevalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updatevalue',
        ),
    ]
