# Generated by Django 4.0.3 on 2022-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_delete_updatevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='productname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
